development:
  validation_framework: :active_model
  database: couch_blog_dummy
test:
  database: couch_blog_dummy_test
  validation_framework: :active_model
production:
  validation_framework: :active_model
  database: couch_blog_dummy
